create table if not exists public.services (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null,
  description text default '',
  image_url text default '',
  featured boolean not null default true,
  created_at timestamptz not null default now()
);

insert into public.services (name, category, description)
select * from (values
  ('High-Level Glass & Alucobond Cleaning', 'Building Exterior', 'Specialized high-level cleaning for glass façades and Alucobond surfaces.'),
  ('High-Level Iron Net Cleaning', 'Building Exterior', 'High-level cleaning and maintenance for iron net and exterior structures.'),
  ('Wall Cleaning', 'Building Exterior', 'Professional exterior wall cleaning for commercial and residential buildings.'),
  ('Resilicon & Silicone Repairing', 'Repair & Maintenance', 'Repairing and maintaining silicone and exterior joints on building surfaces.'),
  ('Wall Cracks Repairing & Repainting', 'Repair & Maintenance', 'Exterior crack repair and repainting services for building walls.'),
  ('General Deep Cleaning Service', 'Cleaning Service', 'Deep cleaning for spaces that need detailed and careful treatment.'),
  ('High-Level Maintaining Service', 'Maintenance', 'High-level building maintenance support for exterior surfaces.')
) as seed(name, category, description)
where not exists (select 1 from public.services);

alter table public.services enable row level security;

create policy "Public can read services"
on public.services for select
using (true);

create policy "Authenticated users can insert services"
on public.services for insert
to authenticated
with check (true);

create policy "Authenticated users can update services"
on public.services for update
to authenticated
using (true);

create policy "Authenticated users can delete services"
on public.services for delete
to authenticated
using (true);
